name:                lang
version:             0.1.0.0
#synopsis:
#description:
homepage:            https://github.com/jgertm/lang#readme
license:             BSD3
author:              Tim Jäger
maintainer:          jger.tm@gmail.com
copyright:           2018 Tim Jäger
category:            Language
extra-source-files:
- README.md

ghc-options:
  - -fhide-source-paths
  - -freverse-errors
  - -O2
  - -Wall
  - -Wincomplete-uni-patterns
  - -Wincomplete-record-updates
  - -Wcompat
  - -Widentities
  - -Wredundant-constraints
  - -Wmissing-export-lists
  - -Wpartial-fields
  - -fllvm
  # - -Werror

default-extensions:
  - ApplicativeDo
  - AutoDeriveTypeable
  - BangPatterns
  - ConstrainedClassMethods
  - ConstraintKinds
  - DataKinds
  - DefaultSignatures
  - DeriveDataTypeable
  - DeriveFoldable
  - DeriveFunctor
  - DeriveGeneric
  - DeriveLift
  - DeriveTraversable
  - DuplicateRecordFields
  - ExistentialQuantification
  - ExplicitForAll
  - ExtendedDefaultRules
  - FlexibleContexts
  - FlexibleInstances
  - FunctionalDependencies
  - GADTs
  - GeneralizedNewtypeDeriving
  - InstanceSigs
  - KindSignatures
  - LambdaCase
  - MultiParamTypeClasses
  - MultiWayIf
  - NamedFieldPuns
  - NamedWildCards
  - NoMonomorphismRestriction
  - OverloadedLabels
  - OverloadedLists
  - OverloadedStrings
  - PartialTypeSignatures
  - PatternSynonyms
  - PolyKinds
  - QuasiQuotes
  - RankNTypes
  - RoleAnnotations
  - ScopedTypeVariables
  - StandaloneDeriving
  - TemplateHaskell
  - TupleSections
  - TypeApplications
  - TypeFamilies
  - TypeOperators
  - TypeSynonymInstances
  - ViewPatterns

dependencies:
  - ansi-terminal
  - base-noprelude >= 4.7 && < 5
  - containers
  - generic-lens
  - microlens-platform
  - mtl
  - parsec
  - pretty-simple
  - prettyprinter
  - prettyprinter
  - text
  - universum

library:
  source-dirs:        src

executables:
  # langi:
  #   source-dirs:        exe/repl
  #   main:               Main.hs
  #   dependencies:
  #     - lang
  #     - haskeline

  lang:
    source-dirs:        exe/tool
    main:               Main.hs
    dependencies:
      - lang
      - haskeline

tests:
  lang-tests:
    source-dirs:      test
    main:             Spec.hs
    ghc-options:
      - -O0
    dependencies:
      - lang
      - tasty
      - tasty-hunit
