name:                lang
version:             0.1.0.0
#synopsis:
#description:
homepage:            https://github.com/jgertm/lang#readme
license:             BSD3
author:              Tim Jäger
maintainer:          jger.tm@gmail.com
copyright:           2018 Tim Jäger
category:            Language
extra-source-files:
- README.md

ghc-options:
  - -fhide-source-paths
  - -fwarn-incomplete-patterns
  - -fwarn-incomplete-uni-patterns
  - -fwarn-incomplete-record-updates
  - -O2
  - -Wall
  - -Wcompat
  # - -Werror

default-extensions:
  - ApplicativeDo
  - AutoDeriveTypeable
  - BangPatterns
  - ConstrainedClassMethods
  - ConstraintKinds
  - DataKinds
  - DefaultSignatures
  - DeriveDataTypeable
  - DeriveFoldable
  - DeriveFunctor
  - DeriveGeneric
  - DeriveLift
  - DeriveTraversable
  - DuplicateRecordFields
  - ExistentialQuantification
  - ExplicitForAll
  - FlexibleContexts
  - FlexibleInstances
  - FunctionalDependencies
  - GADTs
  - GeneralizedNewtypeDeriving
  - InstanceSigs
  - KindSignatures
  - LambdaCase
  - MultiParamTypeClasses
  - MultiWayIf
  - NamedFieldPuns
  - NamedWildCards
  - NoMonomorphismRestriction
  - OverloadedLabels
  - OverloadedLists
  - OverloadedStrings
  - PartialTypeSignatures
  - PatternSynonyms
  - PolyKinds
  - QuasiQuotes
  - RankNTypes
  - RoleAnnotations
  - ScopedTypeVariables
  - StandaloneDeriving
  - StaticPointers
  - TemplateHaskell
  - TupleSections
  - TypeApplications
  - TypeFamilies
  - TypeInType
  - TypeOperators
  - TypeSynonymInstances
  - UndecidableInstances
  - ViewPatterns
  
dependencies:
  - base >= 4.7 && < 5
  - text
  - parsec

library:
  source-dirs:        src
  # exposed-modules:
  #   - Builtins
  #   - Handlers
  #   - Interpreter
  #   - Parser.Abstract
  #   - Syntax.Abstract
  #   - Types
  dependencies:
    - containers
    - generic-lens
    - generic-lens-labels
    - microlens-platform
    - mtl
    - pretty-simple
    - parsec

executables:
  langi:
    source-dirs:        exe/repl
    main:               Main.hs
    dependencies:
      - lang
      - haskeline

tests:
  lang-tests:
    source-dirs:      test
    main:             Spec.hs
    dependencies:
      - lang
      - tasty
      - tasty-hunit
