name:                lang
version:             0.1.0.0
#synopsis:
#description:
homepage:            https://github.com/jgertm/lang#readme
license:             BSD3
author:              Tim Jäger
maintainer:          jger.tm@gmail.com
copyright:           2018 Tim Jäger
category:            Web
extra-source-files:
- README.md

ghc-options:
  - -fhide-source-paths

dependencies:
  - base >= 4.7 && < 5
  - parsec
  - text

default-extensions:
  - DeriveDataTypeable
  - DeriveFoldable
  - DeriveFunctor
  - DeriveTraversable
  - OverloadedStrings
  - PartialTypeSignatures

library:
  source-dirs:        src
  exposed-modules:
    - Parser.Abstract
    - Syntax.Abstract
    - Types

tests:
  lang-tests:
    source-dirs:      test
    main:             Spec.hs
    dependencies:
      - lang
      - tasty
      - tasty-hunit
